name: Run Slim Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: pdo, pdo_mysql
          coverage: none
  
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Save built files
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: .

  test:
    needs: build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=root" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: .

      - name: Initialize Database
        run: |
          mysql -h 127.0.0.1 -u root --password=root test < database_init.sql

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit test
        env:
            DB_HOST: 127.0.0.1
            DB_DATABASE: test
            DB_USERNAME: root
            DB_PASSWORD: root
